# Generated by Django 3.2.8 on 2021-10-29 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_banner_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='store.product'),
        ),
    ]
