# Generated by Django 3.2.8 on 2021-11-16 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationobject',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_object', to=settings.AUTH_USER_MODEL),
        ),
    ]
