# Generated by Django 3.2.8 on 2021-10-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211028_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selecttemplate',
            name='template_img',
            field=models.ImageField(default='temp_demo/demo.jpg', upload_to='template_img'),
        ),
    ]
