# Generated by Django 3.2.8 on 2021-11-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_selecttemplate_template_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='favicon',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.selecttemplate'),
        ),
        migrations.AddField(
            model_name='mainicon',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.selecttemplate'),
        ),
    ]
