# Generated by Django 3.2.8 on 2021-11-08 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211107_0605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favicon',
            old_name='template',
            new_name='active_template',
        ),
        migrations.RenameField(
            model_name='mainicon',
            old_name='template',
            new_name='active_template',
        ),
    ]
