# Generated by Django 3.2.8 on 2021-11-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20211108_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='active_template',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='active_template',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
