# Generated by Django 3.2.8 on 2021-11-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20211108_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favicon',
            name='image',
            field=models.ImageField(default='favicon/demo.png', upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='image',
            field=models.ImageField(default='main_icon/demo.png', upload_to='main_icon'),
        ),
    ]
