# Generated by Django 3.2.8 on 2021-11-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20211108_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_template', models.CharField(blank=True, default='0', max_length=5, null=True)),
                ('title', models.CharField(default='Home | Cleverange', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='favicon',
            name='active_template',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='mainicon',
            name='active_template',
            field=models.CharField(blank=True, default='0', max_length=5, null=True),
        ),
    ]
