# Generated by Django 3.2.8 on 2021-11-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20211108_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagetitle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
