# Generated by Django 3.2.8 on 2021-11-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cartitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('proccessing', 'proccessing'), ('complete', 'complete')], default='pending', max_length=30),
        ),
    ]
